version: "3.9"

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: ${DB_NAME}
    volumes:
      - mongo-data:/data/db
    networks:
      - nest-gql-monitoring

  api:
    build: .
    container_name: nest-gql-monitoring-backend
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      DB_URL: mongodb://mongo:27017/${DB_NAME}
    networks:
      - nest-gql-monitoring

volumes:
  mongo-data:

networks:
  nest-gql-monitoring:
